SERVICE_HOST: localhost
SERVICE_PORT: 8080
SQL_DB_HOST: localhost
SQL_DB_PORT: 5432
SQL_DB_USER: postgres
SQL_DB_PASS: dongphuong189
POSTGRES_DB: bkzalo

server:
  servlet:
    context-path: '/api'
  compression:
    enabled: true # Enable response compression
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # The comma-separated list of mime types that should be compressed
    min-response-size: 2048 # Compress the response only if the response size is at least 1 KB

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SQL_DB_HOST}:${SQL_DB_PORT}/${POSTGRES_DB}
    username: ${SQL_DB_USER}
    password: ${SQL_DB_PASS}
    hikari: # reference: https://github:com/brettwooldridge/HikariCP#configuration-knobs-baby:
      maxLifetime: 30000
      leakDetectionThreshold: 30000
  jpa:
    properties:
      hibernate:
        format_sql: true # not recommended for production
        order_inserts: true
        jdbc:
          batch_size: 50

#logging:
#  level:
#    root: INFO
#    com.hust.baseweb: DEBUG
#    org:
#      springframework: INFO
#      springframework.security: TRACE
##      hibernate:
##        SQL: DEBUG
##        type:
##          descriptor:
##            sql:
##              BasicBinder: TRACE